### PR TITLE
Support offset and opacity

### PR DESCRIPTION
**Pull request by SylvainCorlay**
...

### CODE REVIEW

**Comment by goanpeca** [comment]
Hi @SylvainCorlay, cool :) I would say that it would be very helpful to have a shadow keyword that would under the curtains do an stack offset with some default parameters (offset plus color). It would be a convenience thing that would make creating a shadowed icon super easy.

**Comment by goanpeca** [comment]
So instead of

```python
# Stack and offset icons
saveall = qta.icon_stack(['fa.save', 'fa.save'],
                                      options=[{'scale_factor': 0.8, 
                                             'offset': (0.2, 0.2),
                                             'color': 'gray'},
                                            {'scale_factor': 0.8}])

```

```python
# Stack and offset icons
        saveall = qta.icon('fa.save', shadow=True)

```

**Comment by goanpeca** [comment]
oops sorry, hit close by accident!!

**Comment by SylvainCorlay** [comment]
OK, this is be a good idea to add higher-level APIs for specific effects like shadow.

**Comment by goanpeca** [comment]
Yep, high level api sound good. In this sense it would make sense to be able to define global defaults for this high level api, so the user can set the shadow defaults once when loading pyqtawesome

**Comment by SylvainCorlay** [comment]
Rebased

**Pull request merged**
